### ISSUE TITLE
Please Cite

### ISSUE THREAD

**Issue by ofirnachum** [LantaoYu/SeqGAN#1]
Hey - looks like you heavily based this code on my implementation at https://github.com/ofirnachum/sequence_gan

It's nice to see that you got it working on bigger problems, but please cite/reference my work.

**Comment by wnzhang** [comment]
No problem. I have added the citation of your repository. Many thanks!!

**Comment by solderzzc** [comment]
哈哈
http://ai.tiegushi.com/t/topic/49
也转载了
