### ISSUE TITLE
Int to Word Mapping needed

### ISSUE THREAD

**Issue by caffeine96** [LantaoYu/SeqGAN#17]
Can you upload the integer to word mappings or the pickle file for the mappings? I am unable to comprehend the data generated in real_data.txt

**Comment by Achilles-96** [comment]
Any response on this?

**Comment by LantaoYu** [comment]
Hi, we provide the more persuasive synthetic data experiments for demonstration in this repository. You may read the "Synthetic Data Experiments" section of this [paper](https://arxiv.org/pdf/1609.05473.pdf) for more details.
