### ISSUE TITLE
Support python3.5.2?

### ISSUE THREAD

**Issue by wangtao1321** [LantaoYu/SeqGAN#22]
Hi,
Would you have idea to support python3.5.2 environment?as Tensorflow for windows only support python3.5.2

**Comment by josaum** [comment]
Hi @wangtao1321 , I just made it work on Py3.5 and windows.

1 - Run the command: 2to3 -w -f all sequence_gan.py
2 - Run the command: 2to3 -w -f all generator.py
3 - Change Line 92 in sequence_gan.py to: 
target_params = pickle.load(open('save/target_params_py3.pkl', 'rb'))

Note that the picke file changed to the suitable py3 version and also add the 'rb' to read the raw binary and don't get overridden by the OS default encoding.

That should make it work, at least it did for me.

Hope it helps!

**Comment by daveanyan** [comment]
Could  you send the code that run on python3.5.2 to my qq e-mail? I want to try to run it?my qq e-mail is 1067196250@qq.com.Thank you very much!
