### ISSUE TITLE
What is the function of rollout.update_params()?

### ISSUE THREAD

**Issue by guotong1988** [LantaoYu/SeqGAN#23]
Why do you do `rollout.update_params()`?
Thank you
Thank you
Thank you
@LantaoYu @wnzhang

**Comment by vanpersie32** [comment]
same question here. According to the paper,  the parameters of roll out policy should be the same with generator. But actually in the code, it is not.

**Comment by eduOS** [comment]
Refer to this [issue](https://github.com/LantaoYu/SeqGAN/issues/29).
