### ISSUE TITLE
How to train and generate from our own Data?

### ISSUE THREAD

**Issue by jpcreamer** [LantaoYu/SeqGAN#3]
Can you provide any guidance on how to train and generate from my own data? I would like to try SeqGAN with various English poetry and prose, but I am not sure how to change this code to train on my own data and then generate new writing.

**Comment by LantaoYu** [comment]
In our code, a synthetic data experiment, we first initialize an oracle model and use it to generate the real data. In the real scenarios, you can just skip the oracle building step and real data generation step and directly load the English poetry data as the real data. Specifically, in https://github.com/LantaoYu/SeqGAN/blob/master/MLE_SeqGAN/sequence_gan.py#L155 , we use the oracle to generate the real data, which is a set of sequences of numbers(index), you can just skip this step and https://github.com/LantaoYu/SeqGAN/blob/master/MLE_SeqGAN/sequence_gan.py#L156 will load the given real data, i.e. the poetry sequences. Note that you should also remove the oracle evaluation function and use your own evaluation function such as BLEU.

**Comment by Crista23** [comment]
@jpcreamer @LantaoYu Could you please post the code for training on custom dataset?
