### ISSUE TITLE
Training on custom dataset 

### ISSUE THREAD

**Issue by WorldHellow** [LantaoYu/SeqGAN#54]
I want to train AOL Search query logs on Seq-GAN to generate queries. Is there an implementation of Seq-GAN that uses Custom Dataset?

**Comment by bhushan23** [comment]
@WorldHellow  we have extended Seq-GAN implementation in PyTorch which allows loading custom data.
here, https://github.com/bhushan23/Transformer-SeqGAN-PyTorch

**Comment by sunwooha** [comment]
Hello! I am currently trying to train Seq-GAN with my custom data using the linked Github repository, but I keep on getting an error:

Traceback (most recent call last):
  File "main.py", line 327, in <module>
    main()
  File "main.py", line 291, in main
    loss = gen_gan_loss(prob, targets, rewards)
  File "/home/solar/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 184, in forward
    loss = loss * reward
RuntimeError: The size of tensor a (110) must match the size of tensor b (11) at non-singleton dimension 1

Could you help me figure out why I am getting this error?
